{% set version = "2.1.1" %}

package:
  name: alinea.astk
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - openalea.core
    - numpy
    - pandas
    - openalea.plantgl
    - pvlib-python
    - pytables
    # hotfix for current packaging error of pytables (see conda-forge/pytables-feedstock#31)
    - snappy [win]

test:
  requires:
    - nose
  imports:
    - alinea.astk
  source_files:
    - test/test_*.py
  commands:
   - nosetests -v

about:
  home: http://github.com/openalea-incubator/astk
  license: CeCILL_C
  summary: The Alinea.astk package provides utilities for simulation of FSPM models.

